import type { Metadata } from "next";
// import { Geist, Geist_Mono, Inter } from "next/font/google";
import { Epilogue, Urbanist } from "@next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { Toaster } from "@/components/ui/sonner";
import CookieConsent from "@/components/common/CookieConsent";

const epilogue = Epilogue({
  subsets: ["latin"],
  variable: "--font-epilogue",
});

const urbanist = Urbanist({
  subsets: ["latin"],
  variable: "--font-urbanist",
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn("h-full", "antialiased", epilogue.variable, urbanist.variable)}
    >
      <body>
        {children}
        <Toaster richColors position="top-right" closeButton />
        <CookieConsent />
      </body>
    </html>
  );
}
